name:                tchan
version:             0.1.0.0
github:              "jchia/tchan"
license:             BSD-3-Clause
author:              "Joshua Chia"
maintainer:          "joshchia@gmail.com"
copyright:           "Copyright (c) 2024 Joshua Chia"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jchia/tchan#readme>

dependencies:
- base >= 4.7 && < 5
- stm
- async
- classy-prelude

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints


executables:
  tchan-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - classy-prelude
    - stm

